# Generated by Django 6.0.1 on 2026-01-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_description', models.CharField(max_length=50, verbose_name='Короткое описание')),
                ('main_text', models.CharField(max_length=100, verbose_name='Основной текст')),
            ],
            options={
                'verbose_name': 'Скидка на данный момент',
                'verbose_name_plural': 'Скидки на данный момент',
                'ordering': ['-created_at'],
            },
        ),
    ]
