# Generated by Django 6.0.1 on 2026-01-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/discount_images'),
        ),
    ]
