# Generated by Django 6.0.1 on 2026-01-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_discount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discount_images/'),
        ),
    ]
